services: 

  
  catalogservice:
    build:
      context: .
      dockerfile: src/CatalogService/Dockerfile
    ports:
      - 5297:5297
      - 7204:7204
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: