receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "otel-collector:9464"
  logging:
    loglevel: debug
  jaeger:
    endpoint: "jaeger:14250"
    tls_enabled: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
