global:
  evaluation_interval: 30s
  scrape_interval: 5s

scrape_configs:
  - job_name: otel
    static_configs:
      - targets:
        - 'otel-collector:8889'
  - job_name: otel-collector
    static_configs:
      - targets:
        - 'otel-collector:8888'
  - job_name: catalogservice
    static_configs:
      - targets:
        - 'catalogservice:5297' # Assuming catalogservice runs on port 5297
  - job_name: prometheus
    static_configs:
      - targets:
        - 'prometheus:9090' # Assuming Prometheus runs on port 9090
