global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: '@example.com'
        send_resolved: true
        from: '@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: '@example.com'
        auth_identity: '@example.com'
        auth_password: '@example.com'
